/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as AuthRegisterRouteImport } from './routes/_auth/register'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as DashboardUsersIndexRouteImport } from './routes/dashboard/users/index'
import { Route as DashboardProfileIndexRouteImport } from './routes/dashboard/profile/index'
import { Route as DashboardCategoriesIndexRouteImport } from './routes/dashboard/categories/index'
import { Route as DashboardUsersIdRouteImport } from './routes/dashboard/users/$id'
import { Route as DashboardReimbursementsNewRouteImport } from './routes/dashboard/reimbursements/new'
import { Route as DashboardReimbursementsIdRouteImport } from './routes/dashboard/reimbursements/$id'
import { Route as DashboardReimbursementsEditIdRouteImport } from './routes/dashboard/reimbursements/edit.$id'

const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const DashboardUsersIndexRoute = DashboardUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardProfileIndexRoute = DashboardProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardCategoriesIndexRoute =
  DashboardCategoriesIndexRouteImport.update({
    id: '/categories/',
    path: '/categories/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardUsersIdRoute = DashboardUsersIdRouteImport.update({
  id: '/users/$id',
  path: '/users/$id',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardReimbursementsNewRoute =
  DashboardReimbursementsNewRouteImport.update({
    id: '/reimbursements/new',
    path: '/reimbursements/new',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardReimbursementsIdRoute =
  DashboardReimbursementsIdRouteImport.update({
    id: '/reimbursements/$id',
    path: '/reimbursements/$id',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardReimbursementsEditIdRoute =
  DashboardReimbursementsEditIdRouteImport.update({
    id: '/reimbursements/edit/$id',
    path: '/reimbursements/edit/$id',
    getParentRoute: () => DashboardRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/reimbursements/$id': typeof DashboardReimbursementsIdRoute
  '/dashboard/reimbursements/new': typeof DashboardReimbursementsNewRoute
  '/dashboard/users/$id': typeof DashboardUsersIdRoute
  '/dashboard/categories/': typeof DashboardCategoriesIndexRoute
  '/dashboard/profile/': typeof DashboardProfileIndexRoute
  '/dashboard/users/': typeof DashboardUsersIndexRoute
  '/dashboard/reimbursements/edit/$id': typeof DashboardReimbursementsEditIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/reimbursements/$id': typeof DashboardReimbursementsIdRoute
  '/dashboard/reimbursements/new': typeof DashboardReimbursementsNewRoute
  '/dashboard/users/$id': typeof DashboardUsersIdRoute
  '/dashboard/categories': typeof DashboardCategoriesIndexRoute
  '/dashboard/profile': typeof DashboardProfileIndexRoute
  '/dashboard/users': typeof DashboardUsersIndexRoute
  '/dashboard/reimbursements/edit/$id': typeof DashboardReimbursementsEditIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteRouteWithChildren
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/reimbursements/$id': typeof DashboardReimbursementsIdRoute
  '/dashboard/reimbursements/new': typeof DashboardReimbursementsNewRoute
  '/dashboard/users/$id': typeof DashboardUsersIdRoute
  '/dashboard/categories/': typeof DashboardCategoriesIndexRoute
  '/dashboard/profile/': typeof DashboardProfileIndexRoute
  '/dashboard/users/': typeof DashboardUsersIndexRoute
  '/dashboard/reimbursements/edit/$id': typeof DashboardReimbursementsEditIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/dashboard/'
    | '/dashboard/reimbursements/$id'
    | '/dashboard/reimbursements/new'
    | '/dashboard/users/$id'
    | '/dashboard/categories/'
    | '/dashboard/profile/'
    | '/dashboard/users/'
    | '/dashboard/reimbursements/edit/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/dashboard'
    | '/dashboard/reimbursements/$id'
    | '/dashboard/reimbursements/new'
    | '/dashboard/users/$id'
    | '/dashboard/categories'
    | '/dashboard/profile'
    | '/dashboard/users'
    | '/dashboard/reimbursements/edit/$id'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/dashboard'
    | '/_auth/login'
    | '/_auth/register'
    | '/dashboard/'
    | '/dashboard/reimbursements/$id'
    | '/dashboard/reimbursements/new'
    | '/dashboard/users/$id'
    | '/dashboard/categories/'
    | '/dashboard/profile/'
    | '/dashboard/users/'
    | '/dashboard/reimbursements/edit/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/dashboard/users/': {
      id: '/dashboard/users/'
      path: '/users'
      fullPath: '/dashboard/users/'
      preLoaderRoute: typeof DashboardUsersIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/profile/': {
      id: '/dashboard/profile/'
      path: '/profile'
      fullPath: '/dashboard/profile/'
      preLoaderRoute: typeof DashboardProfileIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/categories/': {
      id: '/dashboard/categories/'
      path: '/categories'
      fullPath: '/dashboard/categories/'
      preLoaderRoute: typeof DashboardCategoriesIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/users/$id': {
      id: '/dashboard/users/$id'
      path: '/users/$id'
      fullPath: '/dashboard/users/$id'
      preLoaderRoute: typeof DashboardUsersIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/reimbursements/new': {
      id: '/dashboard/reimbursements/new'
      path: '/reimbursements/new'
      fullPath: '/dashboard/reimbursements/new'
      preLoaderRoute: typeof DashboardReimbursementsNewRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/reimbursements/$id': {
      id: '/dashboard/reimbursements/$id'
      path: '/reimbursements/$id'
      fullPath: '/dashboard/reimbursements/$id'
      preLoaderRoute: typeof DashboardReimbursementsIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/reimbursements/edit/$id': {
      id: '/dashboard/reimbursements/edit/$id'
      path: '/reimbursements/edit/$id'
      fullPath: '/dashboard/reimbursements/edit/$id'
      preLoaderRoute: typeof DashboardReimbursementsEditIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface DashboardRouteRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardReimbursementsIdRoute: typeof DashboardReimbursementsIdRoute
  DashboardReimbursementsNewRoute: typeof DashboardReimbursementsNewRoute
  DashboardUsersIdRoute: typeof DashboardUsersIdRoute
  DashboardCategoriesIndexRoute: typeof DashboardCategoriesIndexRoute
  DashboardProfileIndexRoute: typeof DashboardProfileIndexRoute
  DashboardUsersIndexRoute: typeof DashboardUsersIndexRoute
  DashboardReimbursementsEditIdRoute: typeof DashboardReimbursementsEditIdRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardReimbursementsIdRoute: DashboardReimbursementsIdRoute,
  DashboardReimbursementsNewRoute: DashboardReimbursementsNewRoute,
  DashboardUsersIdRoute: DashboardUsersIdRoute,
  DashboardCategoriesIndexRoute: DashboardCategoriesIndexRoute,
  DashboardProfileIndexRoute: DashboardProfileIndexRoute,
  DashboardUsersIndexRoute: DashboardUsersIndexRoute,
  DashboardReimbursementsEditIdRoute: DashboardReimbursementsEditIdRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
